### ISSUE TITLE
【iOS】原生模式下 present 出来的页面在做切后台动作时会被被销毁

### ISSUE THREAD

**Issue by cillyfly** [gdtmobsdk/GDTMobSDK#1]
# 原生模式下 present 出来的页面在做切后台动作时会被被销毁

## 相关描述
具体现象如题所述。
在广告加载后，凡是由 `present` 出来的页面，当做切后台的动作(`iphonex` 向上滑动,其他双击`home`键)

## 测试路径
1.打开`demo`
2.选择原生模板广告
3.任意点开一个广告，此时会`present`出来广告的详情页
4.做切后台动作
5.广告详情页被销毁

## 影响
此`bug`会导致非广告部分由`present`方式调出的页面被销毁，影响业务开发

##  `bug`重现视频地址
https://youtu.be/HI8wRp6J3ZA

**Comment by gdtmobsdk** [comment]
@cillyfly 不好意思现在才回复你，我们已经更新到4.10.2版本，已经解决了这个bug
