### ISSUE TITLE
4.11.5版本集成成功，加载banner广告，回调失败，详情码104001.

### ISSUE THREAD

**Issue by ls10513840** [gdtmobsdk/GDTMobSDK#17]

**Comment by gdtmobsdk** [comment]
建议升级到4.11.6再次尝试一下，如果还有问题，可以联系我们

**Comment by ls10513840** [comment]
> 建议升级到4.11.6再次尝试一下，如果还有问题，可以联系我们

问题已经处理了，是因为另一个小伙伴写了一个URL的分类，全局替换了含有非法字符的URL，所以才导致广告未能显示。
