### ISSUE TITLE
Universal Framework support

### ISSUE THREAD

**Issue by wongzigii** [gdtmobsdk/GDTMobSDK#2]
# Submission Title

Add Universal Framework Support

## Description

Right now, there are two separate frameworks: `GDTAction.framework` and `GDTAction-simulator.framework` included in your SDK archive file. Is it possible to use a universal framework to support different architectures, cause we are suffering inconvenient due to switching the framework binary back and forth.

## Presenter(s)

Name: Zigii Wong
Email: wongzigii@gmail.com

**Comment by gdtmobsdk** [comment]
@wongzigii you can create Universal Framework with libGDTMobSDK.a in " lipo -create" command
