### ISSUE TITLE
官方SDK4.11.5 OC版 demo  Banner2.0广告出不来，报错

### ISSUE THREAD

**Issue by dandanhjj** [gdtmobsdk/GDTMobSDK#20]
2020-03-18 18:04:59.034934+0800 GDTMobSample[17661:770053] [Error] [GDTMob:GDTSettingManager] update sdk setting:{
    antiSpamTestRate = 0;
    "appstore_preload_sampling_rate" = 100;
    beaconOn = 0;
    buglyRate = 100;
    callChainCheckReportRate = 0;
    "clkad_report_sampling_rate" = 100;
    enableMediation = 1;
    eventRate = 10000;
    "expad_report_sampling_rate" = 90;
    feedsADExposureTime = 500;
    "getad_report_sampling_rate" = 30;
    iOSBannerPageUrl = "https://qzonestyle.gtimg.cn/qzone/biz/gdt/mob/sdk/ios/v2/banner.html";
    iOSInterstitialPageUrl = "https://qzonestyle.gtimg.cn/qzone/biz/gdt/mob/sdk/ios/v2/interstitial.html";
    innerBrowserScheme = "weixin,tel,openapp.jdmobile";
    "inner_browser_on" = 1;
    "inter_loadad_count_limit" = 100;
    locationUpdateRate = 360000;
    logERate = 10000;
    mapSdkRatio = 0;
    markets = "";
    miniCardList = "com.ss.android.article.news,com.nuomi";
    miniCardRef = "Tencent-GDT";
    miniCardSupport = 1;
    mmaEnabled = 1;
    "native_loadad_count_limit" = 150;
    perfRate = 100;
    qimeiPackageNameList = "";
    qimeiSamplingRate = 0;
    reachabilityEnabled = 1;
    reqInterval = 900;
    resignActiveEnabled = 1;
    rewardVideoEffectiveTime = 30;
    rewardVideoServerMaxDuration = 61;
    rf = 30000;
    "should_collect_qadid" = 1;
    "show_logo" = 1;
    "spl_conn" = 26;
    "spl_exptime" = 5000;
    "spl_ltime" = 3000;
    "spl_maxrn" = 100;
    splashReqAdCount = 1;
    stop = 0;
    "store_load_to" = 15;
    thirdPartyBrowser = "com.android.browser,com.android.chrome,com.baidu.browser.apps,com.UCMobile,com.tencent.mtt";
    tpl = "https://qzonestyle.gtimg.cn/qzone/biz/gdt/mob/sdk/1.3/sdk.js";
    transitionstoreswitch = 0;
    visibilityCheckReportRate = 0;
}
2020-03-18 18:04:59.097300+0800 GDTMobSample[17661:770053] -[UnifiedBannerViewController unifiedBannerViewFailedToLoad:error:]

**Comment by gdtmobsdk** [comment]
你好，由于当时服务器不稳定，导致数据异常，目前已正常，目前sdk已更新到4.11.6，建议您使用最新版尝试一下
