### ISSUE TITLE
v4.11.6在应用审核时启动闪退

### ISSUE THREAD

**Issue by muyexi** [gdtmobsdk/GDTMobSDK#23]
v4.11.6在应用审核时启动闪退，导致更新被驳回，但在本机上又无法重现。

> Last Exception Backtrace:
0   CoreFoundation                	0x19ad135f0 0x19abe9000 + 1222128
1   libobjc.A.dylib               	0x19aa35bcc 0x19aa30000 + 23500
2   CoreFoundation                	0x19ad690cc 0x19abe9000 + 1573068
3   CoreFoundation                	0x19ad72710 0x19abe9000 + 1611536
4   CoreFoundation                	0x19abeff88 0x19abe9000 + 28552
5   sogoke                        	0x102a233e4 -[GDTSplashAdPreloadManager saveRawData:withPlacementID:hotLaunch:] + 111
6   sogoke                        	0x102a21d18 __79-[GDTSplashAdPreloadManager preloadWithAppId:placementId:loadParams:hotLaunch:]_block_invoke + 463
7   sogoke                        	0x102a4ea1c __85+[GDTAdService newFetchAdWithRequestData:threadId:retryTimes:success:notice:failure:]_block_invoke + 511
8   sogoke                        	0x102a4e2a8 __82+[GDTAdService fetchAdWithRequestData:threadId:retryTimes:success:notice:failure:]_block_invoke + 355
9   libdispatch.dylib             	0x19a9d89a8 0x19a97e000 + 371112
10  libdispatch.dylib             	0x19a9d9524 0x19a97e000 + 374052
11  libdispatch.dylib             	0x19a98b5b4 0x19a97e000 + 54708
12  CoreFoundation                	0x19ac91748 0x19abe9000 + 689992
13  CoreFoundation                	0x19ac8c61c 0x19abe9000 + 669212
14  CoreFoundation                	0x19ac8bc34 0x19abe9000 + 666676
15  GraphicsServices              	0x1a4dd538c 0x1a4dd2000 + 13196
16  UIKitCore                     	0x19edbe22c 0x19e392000 + 10666540
17  sogoke                        	0x102981138 main + 4739384 (main.m:6)
18  libdyld.dylib                 	0x19ab13800 0x19ab12000 + 6144

[sogoke  4-12-20, 12-57 AM.txt](https://github.com/gdtmobsdk/GDTMobSDK/files/4501293/sogoke.4-12-20.12-57.AM.txt)

**Comment by muyexi** [comment]
貌似只有使用CocoaPods集成时出现

**Comment by gdtmobsdk** [comment]
你好，建议您手动集成，并升级到最新版本再次尝试一下
