### ISSUE TITLE
刚更新了最新的sdk，报这样的错误

### ISSUE THREAD

**Issue by czpc** [gdtmobsdk/GDTMobSDK#26]
NSGetSizeAndAlignment(): unsupported type encoding spec 'A' at 'oA]Qpsq]zgq`g)ppppi' in 'oA]Qpsq]zgq`g)ppppi'

追踪到的方法 
[UIButton(GDTExtensions) setGDTfunctione372D0:]
[GDAdManager load]

**Comment by czpc** [comment]
启动就就报错

**Comment by gdtmobsdk** [comment]
已经修复，重新下载更新就可以了

**Comment by jimmyjob** [comment]
我这边Pod 进入最新的SDK 4.11.10 项目启动报错
"NSGetSizeAndAlignment(): unsupported type encoding spec '`' at '`NR^\x7f|~Ruh~oh&\x7f\x7f\x7f\x7ff' in '`NR^\x7f|~Ruh~oh&\x7f\x7f\x7f\x7ff'"

**Comment by jimmyjob** [comment]
这个问题在swift5.0 Xcode 11.6  SDK 4.11.10 中又复现了
pod 'GDTMobSDK', '~> 4.11.10'

**Comment by luxing123** [comment]
> 这个问题在swift5.0 Xcode 11.6 SDK 4.11.10 中又复现了
> pod 'GDTMobSDK', '~> 4.11.10'

解决了吗?我也有这个问题
