### ISSUE TITLE
尝试接入react-native,发现很难

### ISSUE THREAD

**Issue by Darkhorse-Fraternity** [gdtmobsdk/GDTMobSDK#3]
# Submission Title

## Description
返回的是View的数组，发现很难通过rn 自带的模式传递

[Description that is 1-2 paragraphs (75 - 150 words)]

Type: [talk | panel | workshop | demos | performance | other (describe!)]  
Length: [30 minutes | 1 hour | 2 hour | half-day]  
Additional considerations: [e.g., max number of participants, access]  

## Session Objective

[Identify 1-3 key objectives for the session (could be participant takeaways)]

## Material and Technical Requirements

[List materials you as presenter require AND any participant materials (indicate if there would be support required for a purchase/cost). Include equipment, technical, and installation requirements if applicable. We will aim to accommodate where possible]

## Presenter(s)

Name: Your Name  
Email: name@youremail.com  
Url(s): [yourwebsite.com](url to website), [yourotherwebsite.com](url to another website)  
Twitter: [@you](url to twitter account)  
GitHub: [you](url to GitHub account)  

Interested in attending the sprint July 16-18: [Y|N]  
Interested in a community billet: [host|billet|N]

## Presenter Bio

[Bio that is under 1 paragraph (50 - 75 words)]

[If multiple presenters, please provide info and bio for all]

**Comment by gdtmobsdk** [comment]
@Darkhorse-Fraternity 问题已记录，我们会反馈给开发
