### ISSUE TITLE
你好，更新sdk后，出现警告⚠️

### ISSUE THREAD

**Issue by alex0811** [gdtmobsdk/GDTMobSDK#4]
你好，更新最新版本sdk4.10.2，xcode编译后出现如下两个warning：
ld: warning: instance method 'setTagDict:' in category from /Users/jianguo/Desktop/S/TXReader/Pods/GDTMobSDK/lib/libGDTMobSDK.a(GDTSplashAd.o) overrides method from class in /Users/jianguo/Desktop/S/TXReader/Pods/GDTMobSDK/lib/libGDTMobSDK.a(GDTSplashAd.o)
ld: warning: instance method 'tagDict' in category from /Users/jianguo/Desktop/S/TXReader/Pods/GDTMobSDK/lib/libGDTMobSDK.a(GDTSplashAd.o) overrides method from class in /Users/jianguo/Desktop/S/TXReader/Pods/GDTMobSDK/lib/libGDTMobSDK.a(GDTSplashAd.o)

**Comment by gdtmobsdk** [comment]
@alex0811 尝试从本仓库中重新下载一份试试，部分优化了
