### ISSUE TITLE
开屏广告不消失

### ISSUE THREAD

**Issue by LittleWhiteRabbitKJ** [gdtmobsdk/GDTMobSDK#9]
我升级了Xcode到11之后，重新跑一遍项目，发现开屏广告倒计时结束不会自动退出，是怎么回事呢？点击跳过按钮，也没有反应！
从AppStore下载的版本还是可以正常退出的。

**Comment by JonorZhang** [comment]
> 我升级了Xcode到11之后，重新跑一遍项目，发现开屏广告倒计时结束不会自动退出，是怎么回事呢？点击跳过按钮，也没有反应！
> 从AppStore下载的版本还是可以正常退出的。

你的GDTSplashAd对象是不是临时(局部)变量？如果是，请改成全局变量，以避免提前释放GDTSplashAd对象。

**Comment by LittleWhiteRabbitKJ** [comment]
是的，我也是按照文档写的。可能文档没有及时更新。按照您说的已经解决了。感谢您的反馈。
